import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

  <head>

  <script
          dangerouslySetInnerHTML={{
            __html: `

            <link rel="shortcut icon" href="TemplateData/Icon.ico">    
            <link rel="stylesheet" href="TemplateData/style.css">
            <script src="TemplateData/UnityProgress.js"></script>
            <script src="Build/UnityLoader.js"></script>
            <script>
              var unityInstance = UnityLoader.instantiate("unityContainer", "Build/230210.json", {onProgress: UnityProgress});
            </script>

				`,
			}}
        />


  </head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
